export enum ErrorCodes {
  // 1inch API errors
  ONEINCH_API_UNAVAILABLE = 'ONEINCH_API_UNAVAILABLE',
  METADATA_FETCH_FAILED = 'METADATA_FETCH_FAILED',
  PRICE_FETCH_FAILED = 'PRICE_FETCH_FAILED',

  // Graph errors
  GRAPH_UNAVAILABLE = 'GRAPH_UNAVAILABLE',
  OPERATOR_NOT_FOUND = 'OPERATOR_NOT_FOUND',
  INSUFFICIENT_DATA = 'INSUFFICIENT_DATA',

  // General errors
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  TIMEOUT_ERROR = 'TIMEOUT_ERROR',
  CACHE_ERROR = 'CACHE_ERROR',
}
